DinamicCV/Controllers/HomeController.cs
using DinamicCV.Data;
using DinamicCV.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace DinamicCV.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext db)
        {
            _logger = logger;
            this.db = db;
        }

        public async Task<IActionResult> Index()
        {

            
            List<WorkData> trabalhos = await db.WorkData                
                .ToListAsync();

            ListaWorkDataViewModel modelo = new ListaWorkDataViewModel
            {
                WorkDatas = trabalhos
            };

            return base.View(modelo);

        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DinamicCV/Controllers/WorkDatasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DinamicCV.Data;
using DinamicCV.Models;
using Microsoft.AspNetCore.Authorization;

namespace DinamicCV.Controllers
{
   [Authorize]
    public class WorkDatasController : Controller
    {
        
        private readonly ApplicationDbContext db;

        public WorkDatasController(ApplicationDbContext context)
        {
            db = context;
        }

        // GET: WorkDatas
        public async Task<IActionResult> Index(int pagina = 1)
        {

            Pagination paginacao = new Pagination
            {
                TotalItems = await db.WorkData.CountAsync(),
                PaginaAtual = pagina
            };

            List<WorkData> trabalhos = await db.WorkData
                .Skip(paginacao.ItemsPorPagina * (pagina - 1))
                .Take(paginacao.ItemsPorPagina)
                .ToListAsync();

            ListaWorkDataViewModel modelo = new ListaWorkDataViewModel
            {
                Paginacao = paginacao,
                WorkDatas = trabalhos
            };

            return base.View(modelo);

            //return View(await _context.WorkData.ToListAsync());
        }

        // GET: WorkDatas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var workData = await db.WorkData
                .FirstOrDefaultAsync(m => m.WorkDataId == id);
            if (workData == null)
            {
                return NotFound();
            }

            return View(workData);
        }

        // GET: WorkDatas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: WorkDatas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("WorkDataId,Employer,InitialDate,FinalDate,JobTitle,JobDescription")] WorkData workData)
        {
            if (ModelState.IsValid)
            {
                db.Add(workData);
                await db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(workData);
        }

        // GET: WorkDatas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var workData = await db.WorkData.FindAsync(id);
            if (workData == null)
            {
                return NotFound();
            }
            return View(workData);
        }

        // POST: WorkDatas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("WorkDataId,Employer,InitialDate,FinalDate,JobTitle,JobDescription")] WorkData workData)
        {
            if (id != workData.WorkDataId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    db.Update(workData);
                    await db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WorkDataExists(workData.WorkDataId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(workData);
        }

        // GET: WorkDatas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var workData = await db.WorkData
                .FirstOrDefaultAsync(m => m.WorkDataId == id);
            if (workData == null)
            {
                return NotFound();
            }

            return View(workData);
        }

        // POST: WorkDatas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var workData = await db.WorkData.FindAsync(id);
            db.WorkData.Remove(workData);
            await db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool WorkDataExists(int id)
        {
            return db.WorkData.Any(e => e.WorkDataId == id);
        }
    }
}

DinamicCV/Views/Home/Index.cshtml
@model ListaWorkDataViewModel
@{
    ViewData["Title"] = "Página Inicial";
}

<div class="container text-center">
    <h1 class="row">@Greatings.Saudacao()</h1>

</div>

<div class="container">
    <hr>
    <div class="row">
        <div class="col-6">
            <h1>António Caldeira</h1>
        </div>
        <div class="col-6">
            <p class="text-right"><a href="~/img/cv.pdf" download>Download my Resume </a><a class="btn btn-primary" asp-action="Index" asp-controller="WorkDatas">Editar CV</a></p>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-8 col-sm-12">
            <div class="media">
                <img class="mr-3" src="~/img/foto.jpg" alt="Jeff Goldblum photo" width="115" height="115">
                <div class="media-body">
                    <h5 class="mt-0">.NET Developer</h5>
                    I develop web applications for business systems using C# and .NET Core. I also provide support and maintenance for applications, develop and maintain coding documentation, project progress reports and application maintenance logs.
                </div>
            </div>
        </div>
        <div class="col-md-4 col-sm-12">
            <div class="row justify-content-md-around m-1">
                <address>
                    <strong>António Caldeira</strong><br>
                    Av. Francisco Sá Borrego, 50<br>
                    6300-559<br>
                    <abbr title="Phone">P:</abbr> (351) 962583527<br>
                    <a href="mailto:#">antoniocaldeira@yahoo.com</a>
                </address>
            </div>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-6 col-sm-12">
            <h2>Education</h2>
            <hr>
            <div class="row">
                <div class="col-6">
                    <h4>Instituto Politécnico Portalegre (Portalegre Polytechnic Institute) IPP</h4>
                </div>
                <div class="col-6">
                    <h5 class="text-right"><span aria-hidden="true"></span> Jan 2002 - Dec 2002</h5>
                </div>
            </div>
            <h5><span class="badge badge-secondary">Masters</span></h5>
            <p>Strategic Management</p>
            <div class="row">
                <div class="col-6">
                    <h4>IPP</h4>
                </div>
                <div class="col-6">
                    <h5 class="text-right"><span aria-hidden="true"></span> Jan 1993 - Dec 1996</h5>
                </div>
            </div>
            <h5><span class="badge badge-secondary">Bachelors</span></h5>
            <p>Business Management and Entrepreneurship</p>
        </div>
        <div class="col-md-6 col-sm-12">
            <h2>Skill Set</h2>
            <hr>
            <div class="progress mt-4">
                <div class="progress-bar bg-success" role="progressbar" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100" style="width: 85%"> .NET Core</div>
            </div>
            <div class="progress mt-4">
                <div class="progress-bar bg-success" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%"> C#</div>
            </div>
            <div class="progress mt-4">
                <div class="progress-bar bg-success" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width: 70%"> Razor Pages</div>
            </div>
            <div class="progress mt-4">
                <div class="progress-bar bg-info" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%"> Blazer Pages</div>
            </div>
            <div class="progress mt-4">
                <div class="progress-bar bg-warning" role="progressbar" aria-valuenow="55" aria-valuemin="0" aria-valuemax="100" style="width: 55%"> CSS</div>
            </div>
            <div class="progress mt-4">
                <div class="progress-bar bg-danger" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 50%"> HTML</div>
            </div>
            <div class="progress mt-4">
                <div class="progress-bar bg-danger" role="progressbar" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100" style="width: 50%"> Javascript</div>
            </div>
        </div>
    </div>
    <hr>
    <h2>Work Experience</h2>
    <hr>

    
    <div>
        @foreach (var item in Model.WorkDatas)
        {
            <div class="row">
                <div class="col-md-6 col-sm-12">
                    <div class="row">
                        <div class="col-5">
                            <h4>@Html.DisplayFor(modelItem => item.Employer)</h4>
                        </div>
                        <div class="col-6">
                            <h5 class="text-right"><span aria-hidden="true"></span> @Html.DisplayFor(modelItem => item.InitialDate) - @Html.DisplayFor(modelItem => item.FinalDate)</h5>
                        </div>
                    </div>
                    <h5><span class="badge badge-secondary">@Html.DisplayFor(modelItem => item.JobTitle)</span></h5>
                    <p>@Html.DisplayFor(modelItem => item.JobDescription)</p>
                </div>
            </div>
        }
     </div>               

    
            <hr>
            <h2>Portfolio</h2>
            <hr>
            <div class="container">
                <div class="row text-center">
                    <div class="col-sm-6 col-12 p-0"><img class="img-thumbnail" src="~/img/java_tech.jpg" alt="Logotipo do Java" width="300" height="300"></div>
                    <div class="col-sm-6 col-12 p-0"><img class="img-thumbnail" src="~/img/1_iIXOmGDzrtTJmdwbn7cGMw.png" alt="Java Logo" width="400" height="300"></div>
                </div>
                <div class="row text-center">
                    <div class="col-sm-6 col-12 p-0"><img class="img-thumbnail" src="~/img/android-10-google.jpg" alt="android 10 logo" width="300" height="400"></div>
                    <div class="col-sm-6 col-12 p-0"><img class="img-thumbnail" src="~/img/Android_phone.png" alt="android phone logo" width="400" height="300"></div>
                </div>
            </div>
            <hr>
            <h2>Contact</h2>
            <hr>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8  col-12 jumbotron">
                        <form>
                            <div class="form-group">
                                <label for="name">Name</label>
                                <input type="text" class="form-control" id="name" name="name" placeholder="Name">
                            </div>
                            <div class="form-group">
                                <label for="email">E-Mail</label>
                                <input type="email" class="form-control" id="email" name="email" placeholder="Email Address" aria-describedby="emailHelp">
                                <span id="emailHelp" class="form-text text-muted" style="display: none;">Please enter a valid e-mail address.</span>
                            </div>
                            <div class="form-group">
                                <label for="message">Message</label>
                                <textarea rows="10" cols="100" class="form-control" id="message" name="message" placeholder="Message" aria-describedby="messageHelp"></textarea>
                                <span id="messageHelp" class="form-text text-muted" style="display: none;">Please enter a message.</span>
                            </div>
                            <div class="text-center">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>


        </div>
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="../../PHP/js/jquery-3.3.1.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="../../PHP/js/popper.min.js"></script>
<script src="../../PHP/js/bootstrap-4.3.1.js"></script>